# Generated by Django 5.2.6 on 2025-09-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
    ]
