# Generated by Django 5.2.6 on 2025-09-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='가격'),
        ),
    ]
