# Generated by Django 5.2.6 on 2025-09-19 02:31

from django.db import migrations, models
import django.db.models.deletion

def set_default_author(apps, schema_editor):
    Announcement = apps.get_model('announcements', 'Announcement')
    User = apps.get_model('auth', 'User')
    # Assuming a superuser with id=1 exists. If not, create one or change this ID.
    # You might want to handle cases where no user exists more robustly.
    try:
        default_user = User.objects.get(id=1)
    except User.DoesNotExist:
        # Handle case where default user does not exist, e.g., create one or raise an error
        # For now, let's assume it exists or will be created.
        print("WARNING: Default user with ID 1 not found. Please create a superuser or adjust the migration.")
        return

    for announcement in Announcement.objects.filter(author__isnull=True):
        announcement.author = default_user
        announcement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_author'),
        ('auth', '0012_alter_user_first_name_max_length'), # Add dependency on auth app migration
    ]

    operations = [
        migrations.RunPython(set_default_author, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='auth.user'),
        ),
    ]